#!/bin/sh

# Better OS/400 detection: see Bugzilla 31132
os400=false
case "`uname`" in
OS400*) os400=true;;
esac

# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# unset CATALINA_HOME in case user has it set, so it won't interfere with our tomcat
unset CATALINA_HOME
unset CATALINA_BASE

PRGDIR=`dirname "$PRG"`
START_EXECUTABLE=tomcat/bin/startup.sh
PORTALSAMPLEPROPERTIES=tomcat/webapps/webapp/WEB-INF/classes/portal_sample.properties
PORTALPROPERTIES=tomcat/webapps/webapp/WEB-INF/classes/portal.properties
WEBAPPDIR=tomcat/webapps/webapp
WEBAPPWAR=tomcat/webapps/webapp.war

VLESAMPLEPROPERTIES=tomcat/webapps/vlewrapper/WEB-INF/classes/vle_sample.properties
VLEPROPERTIES=tomcat/webapps/vlewrapper/WEB-INF/classes/vle.properties
VLEWRAPPERDIR=tomcat/webapps/vlewrapper
VLEWRAPPERWAR=tomcat/webapps/vlewrapper.war

CURRICULUMDIR=tomcat/webapps/curriculum

STUDENTUPLOADSDIR=tomcat/webapps/studentuploads

# Check if portal.properties exists. if it doesn't, unzip webapp.war and fill in appropriate values
if [ ! -f "$PRGDIR"/"$PORTALPROPERTIES" ]; then
   echo "unzipping webapp.war file and setting values in portal.properties"
   unzip "$PRGDIR"/"$WEBAPPWAR" -d "$PRGDIR"/"$WEBAPPDIR"
   # copy portal_sample.properties to portal.properties
   cp "$PRGDIR"/"$PORTALSAMPLEPROPERTIES" "$PRGDIR"/"$PORTALPROPERTIES"
   # append curriculum_base_dir to portal.properties
   echo "curriculum_base_dir=$PRGDIR/$CURRICULUMDIR" >> "$PRGDIR"/"$PORTALPROPERTIES"
   # append studentuploads_base_dir to portal.properties
   echo "studentuploads_base_dir=$PRGDIR/$STUDENTUPLOADSDIR" >> "$PRGDIR"/"$PORTALPROPERTIES"
   # append hibernate settings
   echo "dbType=hsqldb" >> "$PRGDIR"/"$PORTALPROPERTIES" 
   echo "hibernate.connection.username=sa" >> "$PRGDIR"/"$PORTALPROPERTIES" 
   echo "hibernate.connection.password=" >> "$PRGDIR"/"$PORTALPROPERTIES" 
   echo "hibernate.connection.url=jdbc:hsqldb:file:$PRGDIR/tomcat/database/sail_database;user=sa;shutdown=true" >> "$PRGDIR"/"$PORTALPROPERTIES" 
   echo "hibernate.connection.driver_class=org.hsqldb.jdbcDriver" >> "$PRGDIR"/"$PORTALPROPERTIES" 
   echo "hibernate.dialect=org.hibernate.dialect.HSQLDialect" >> "$PRGDIR"/"$PORTALPROPERTIES" 
   echo "hibernate.hbm2ddl.auto=create" >> "$PRGDIR"/"$PORTALPROPERTIES" 
   echo "hibernate.showsql=true" >> "$PRGDIR"/"$PORTALPROPERTIES" 
else
	echo "portal.properties exists. settings all set"
fi


# Check if vle.properties exists. if it doesn't, unzip vlewrapper.war and fill in appropriate values
if [ ! -f "$PRGDIR"/"$VLEPROPERTIES" ]; then
   echo "unzipping vlewrapper.war file and setting values in vle.properties"
   unzip "$PRGDIR"/"$VLEWRAPPERWAR" -d "$PRGDIR"/"$VLEWRAPPERDIR"
   # copy vle_sample.properties to vle.properties
   cp "$PRGDIR"/"$VLESAMPLEPROPERTIES" "$PRGDIR"/"$VLEPROPERTIES"
   # append vlewrapperBaseDir to vle.properties
   echo "vlewrapperBaseDir=$PRGDIR/$VLEWRAPPERDIR" >> "$PRGDIR"/"$VLEPROPERTIES"
   # append hibernate settings
   echo "hibernate.connection.username=sa" >> "$PRGDIR"/"$VLEPROPERTIES" 
   echo "hibernate.connection.password=" >> "$PRGDIR"/"$VLEPROPERTIES" 
   echo "hibernate.connection.url=jdbc:hsqldb:file:$PRGDIR/tomcat/database/vle_database;user=sa;shutdown=true" >> "$PRGDIR"/"$VLEPROPERTIES" 
   echo "hibernate.connection.driver_class=org.hsqldb.jdbcDriver" >> "$PRGDIR"/"$VLEPROPERTIES" 
   echo "hibernate.dialect=org.hibernate.dialect.HSQLDialect" >> "$PRGDIR"/"$VLEPROPERTIES" 
   echo "hibernate.hbm2ddl.auto=create" >> "$PRGDIR"/"$VLEPROPERTIES" 
   echo "hibernate.showsql=true" >> "$PRGDIR"/"$VLEPROPERTIES" 
else
	echo "vle.properties exists. settings all set"
fi

# Check that target executable exists
if $os400; then
  # -x will Only work on the os400 if the files are:
  # 1. owned by the user
  # 2. owned by the PRIMARY group of the user
  # this will not work if the user belongs in secondary groups
  eval
else
  if [ ! -x "$PRGDIR"/"$START_EXECUTABLE" ]; then
    echo "Cannot find $PRGDIR/$START_EXECUTABLE"
    echo "The file is absent or does not have execute permission"
    echo "This file is needed to run this program"
    exit 1
  fi
fi

exec "$PRGDIR"/"$START_EXECUTABLE" start "$@"