#!/bin/sh

# Better OS/400 detection: see Bugzilla 31132
os400=false
case "`uname`" in
OS400*) os400=true;;
esac

# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# unset CATALINA_HOME and CATALINA_BASE in case the user have it set, so they won't interfere with our tomcat
unset CATALINA_HOME
unset CATALINA_BASE

PRGDIR=`dirname "$PRG"`
START_EXECUTABLE=tomcat/bin/startup.sh
WISESAMPLEPROPERTIES=tomcat/webapps/wise/WEB-INF/classes/wise_sample.properties
WISEPROPERTIES=tomcat/webapps/wise/WEB-INF/classes/wise.properties
WISEDIR=tomcat/webapps/wise
WISEWAR=tomcat/webapps/wise.war

CURRICULUMDIR=tomcat/webapps/curriculum

STUDENTUPLOADSDIR=tomcat/webapps/studentuploads
WISEHOMEPAGEWEBLOC="WISE Homepage.webloc"

# get user local ip address and set it in WISE_USER_IP. First check to see if en0,en1,en2,en3,en4 are set. If not, use localhost.
WISE_USER_IP=`ipconfig getifaddr en0`

if [ -z "$WISE_USER_IP" ]; then
  	WISE_USER_IP=`ipconfig getifaddr en1`	
	if [ -z "$WISE_USER_IP" ]; then
	  	WISE_USER_IP=`ipconfig getifaddr en2`	
		if [ -z "$WISE_USER_IP" ]; then
		  	WISE_USER_IP=`ipconfig getifaddr en3`	
			if [ -z "$WISE_USER_IP" ]; then
			  	WISE_USER_IP=`ipconfig getifaddr en4`	
			fi			
		fi		
	fi	
fi

# if user local ip address is still not set, assume that user is not connected to the LAN, so use "localhost"
if [ -z "$WISE_USER_IP" ]; then
  	WISE_USER_IP="localhost"	
fi			

echo "WISE_USER_IP: $WISE_USER_IP"



# Check if wise.properties exists. if it doesn't, unzip wise.war
if [ ! -f "$PRGDIR"/"$WISEPROPERTIES" ]; then
   echo "unzipping wise.war file and setting values in wise.properties"
   unzip "$PRGDIR"/"$WISEWAR" -d "$PRGDIR"/"$WISEDIR"
fi

# copy portal_sample.properties to portal.properties, fill in appropriate values
#cp "$PRGDIR"/"$WISESAMPLEPROPERTIES" "$PRGDIR"/"$WISEPROPERTIES"

# before we start appending, make sure the file ends in a new line
echo "" >> "$PRGDIR"/"$WISEPROPERTIES"

# append curriculum_base_dir to portal.properties
echo "curriculum_base_dir=$PRGDIR/$CURRICULUMDIR" >> "$PRGDIR"/"$WISEPROPERTIES"
# append studentuploads_base_dir to portal.properties
echo "studentuploads_base_dir=$PRGDIR/$STUDENTUPLOADSDIR" >> "$PRGDIR"/"$WISEPROPERTIES"
# append hibernate settings
echo "dbType=hsqldb" >> "$PRGDIR"/"$WISEPROPERTIES" 
echo "hibernate.connection.username=sa" >> "$PRGDIR"/"$WISEPROPERTIES" 
echo "hibernate.connection.password=" >> "$PRGDIR"/"$WISEPROPERTIES" 
echo "hibernate.connection.url=jdbc:hsqldb:file:$PRGDIR/tomcat/database/wise_database;user=sa;shutdown=true" >> "$PRGDIR"/"$WISEPROPERTIES" 
echo "hibernate.connection.driver_class=org.hsqldb.jdbcDriver" >> "$PRGDIR"/"$WISEPROPERTIES" 
echo "hibernate.dialect=org.hibernate.dialect.HSQLDialect" >> "$PRGDIR"/"$WISEPROPERTIES" 
if [ ! -f "$PRGDIR/tomcat/database/wise_database.script" ]; then
	echo "hibernate.hbm2ddl.auto=create" >> "$PRGDIR"/"$WISEPROPERTIES"
fi
echo "hibernate.showsql=true" >> "$PRGDIR"/"$WISEPROPERTIES" 

# Set user ip address in portal.properties. Need to do this each time as the address may have changed since last time WISELocal was run.
sed -i -e "s/localhost/$WISE_USER_IP/g" "$PRGDIR"/"$WISEPROPERTIES"


# Set user ip address in WISE Homepage webloc file. Need to do this each time as the address may have changed since last time WISELocal was run.
sed -i -e "s/<string>.*<\/string>/<string>http:\/\/$WISE_USER_IP:8080\/wise\/index.html<\/string>/g" "$PRGDIR"/"$WISEHOMEPAGEWEBLOC"

# Check that target executable exists
if $os400; then
  # -x will Only work on the os400 if the files are:
  # 1. owned by the user
  # 2. owned by the PRIMARY group of the user
  # this will not work if the user belongs in secondary groups
  eval
else
  if [ ! -x "$PRGDIR"/"$START_EXECUTABLE" ]; then
    echo "Cannot find $PRGDIR/$START_EXECUTABLE"
    echo "The file is absent or does not have execute permission"
    echo "This file is needed to run this program"
    exit 1
  fi
fi

exec "$PRGDIR"/"$START_EXECUTABLE" start "$@"